name: Publish Gem

on: workflow_dispatch

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/check.yml
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/test.yml

  push:
    needs: [check, test]
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    environment: release

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.2.4'
      # - uses: rubygems/release-gem@v1
