name: Test

on:
  push:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.1'
          - '3.2.4'
          - '3.1.5'
          - '3.0.6'
          - '2.7.8'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake spec
