name: Test

on:
  push:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ruby:${{ matrix.ruby_version }}
      # https://github.com/actions/runner/issues/2033#issuecomment-1598547465
      # fatal: detected dubious ownership in repository
      options: --user 1001
    name: Test ${{ matrix.ruby_version }}
    strategy:
      matrix:
        ruby_version:
          - '3.3'
          - '3.2'
          - '3.1'
          - '3.0'
          - '2.7'
    steps:
    - uses: actions/checkout@v4
    - name: Ruby version
      run: ruby -v
    - name: Gem version
      run: gem -v
    - name: Bundler version
      run: bundle -v
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake spec
